# netlify.toml (for sydneyot.com)
[[redirects]]
from = "/signpad/*"
to = "https://effulgent-lolly-8462e0.netlify.app/signpad/:splat"
status = 200                                                     # ← silent proxy, never tells the browser to change URL
force = true
conditions = { Host = ["sydneyot.com", "www.sydneyot.com"] }
